/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFISH, IFISHInterface } from "../IFISH";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFISH__factory {
  static readonly abi = _abi;
  static createInterface(): IFISHInterface {
    return new utils.Interface(_abi) as IFISHInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IFISH {
    return new Contract(address, _abi, signerOrProvider) as IFISH;
  }
}
