/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFISHNFT, IFISHNFTInterface } from "../IFISHNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_seed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_remainingReward",
        type: "uint256",
      },
    ],
    name: "mintFromExecutor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFISHNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IFISHNFTInterface {
    return new utils.Interface(_abi) as IFISHNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFISHNFT {
    return new Contract(address, _abi, signerOrProvider) as IFISHNFT;
  }
}
